const C2_STORAGE_KEY='prfConcept2Results';
const c2Results=()=>JSON.parse(localStorage.getItem(C2_STORAGE_KEY)||'[]');
const c2Save=rows=>localStorage.setItem(C2_STORAGE_KEY,JSON.stringify(rows));
const c2Date=row=>(row.dateUtc||row.date||'').slice(0,10);
const c2Seconds=value=>(Number(value)||0)/10;
const c2Split=row=>row.distance?c2Seconds(row.time)*500/row.distance:0;
const c2Watts=row=>{const s=c2Split(row);return s?2.8/Math.pow(s/500,3):0};
const c2Clock=seconds=>{const total=Math.round(seconds*10),mins=Math.floor(total/600),secs=((total%600)/10).toFixed(1).padStart(4,'0');return `${mins}:${secs}`};
const c2Machine=type=>({rower:'RowErg',dynamic:'Dynamic',slides:'RowErg on slides',skierg:'SkiErg',bike:'BikeErg',water:'On water'}[type]||type||'Erg');

function c2IntervalRows(row){const intervals=row.intervals?.length?row.intervals:row.splits||[];if(!intervals.length)return '';return `<div class="c2-intervals"><div class="c2-interval c2-head"><span>Rep</span><span>Dist</span><span>Time</span><span>Split</span><span>SPM</span><span>HR</span></div>${intervals.map((item,i)=>{const split=item.distance&&item.time?c2Clock(c2Seconds(item.time)*500/item.distance):'—',hr=item.heart_rate?.average||item.heart_rate?.ending||'—';return `<div class="c2-interval"><span>${i+1}</span><span>${item.distance||'—'} m</span><span>${item.time?c2Clock(c2Seconds(item.time)):'—'}</span><span>${split}</span><span>${item.stroke_rate||'—'}</span><span>${hr}</span></div>`}).join('')}</div>`}
function c2Summary(row){const avgHr=row.heartRate?.average||row.heartRate?.ending;return [row.distance?`${Number(row.distance).toLocaleString()} m`:null,row.time?row.timeFormatted||c2Clock(c2Seconds(row.time)):null,c2Split(row)?`${c2Clock(c2Split(row))}/500m`:null,c2Watts(row)?`${Math.round(c2Watts(row))} W`:null,row.strokeRate?`${row.strokeRate} spm`:null,avgHr?`${avgHr} bpm`:null].filter(Boolean).join(' · ')}
function renderC2Day(){const host=document.getElementById('concept2Day');if(!host)return;const rows=c2Results().filter(row=>c2Date(row)===key(date));host.innerHTML=rows.map(row=>`<button class="c2-day-card" data-c2-id="${row.id}"><span class="c2-badge">Concept2</span><strong>${c2Machine(row.type)}</strong><span>${c2Summary(row)}</span><span class="status">›</span></button>`).join('');host.querySelectorAll('[data-c2-id]').forEach(button=>button.onclick=()=>openC2Result(rows.find(row=>String(row.id)===button.dataset.c2Id)))}
function openC2Result(row){detailBody.innerHTML=`<h2>${c2Machine(row.type)} workout</h2><p class="muted">${(row.date||'').replace(' ',' · ')}</p><div class="c2-metrics">${c2Summary(row).split(' · ').map(value=>`<span>${value}</span>`).join('')}</div>${c2IntervalRows(row)}${row.comments?`<p>${esc(row.comments)}</p>`:''}<p class="c2-source">Synced from Concept2${row.verified?' · Verified':''}</p>`;detail.showModal()}
function renderConcept2(){const host=document.getElementById('concept2List'),rows=c2Results().sort((a,b)=>(b.date||'').localeCompare(a.date||'')).slice(0,12);if(!rows.length){host.innerHTML='<p class="muted">No Concept2 workouts synced yet.</p>';return}host.innerHTML=rows.map(row=>`<button class="c2-result" data-c2-id="${row.id}"><span><strong>${c2Machine(row.type)}</strong><small>${(row.date||'').slice(0,16).replace(' ',' · ')}</small></span><span>${c2Summary(row)}</span><span class="status">›</span></button>`).join('');host.querySelectorAll('[data-c2-id]').forEach(button=>button.onclick=()=>openC2Result(rows.find(row=>String(row.id)===button.dataset.c2Id)))}
async function syncConcept2(){const button=document.getElementById('syncConcept2'),status=document.getElementById('concept2Status');button.disabled=true;button.textContent='Syncing…';status.textContent='Contacting your Concept2 Logbook…';const from=new Date();from.setDate(from.getDate()-120);try{const response=await fetch(`/api/concept2/results?from=${from.toISOString().slice(0,10)}`,{headers:{Accept:'application/json'}}),payload=await response.json();if(!response.ok)throw new Error(payload.error||'Unable to sync Concept2.');const existing=new Map(c2Results().map(row=>[String(row.id),row]));payload.data.forEach(row=>existing.set(String(row.id),row));c2Save([...existing.values()]);localStorage.setItem('prfConcept2SyncedAt',payload.syncedAt);status.textContent=`Synced ${payload.data.length} recent workout${payload.data.length===1?'':'s'}.`;renderConcept2();renderC2Day();renderProgress()}catch(error){status.textContent=error.message||'Unable to sync Concept2 right now.'}finally{button.disabled=false;button.textContent='Sync Concept2'}}
const baseRender=render;render=function(){baseRender();renderC2Day()};
const baseRenderProgress=renderProgress;renderProgress=function(){baseRenderProgress();const rows=c2Results();if(rows.length){const imported=rows.slice().sort((a,b)=>(b.date||'').localeCompare(a.date||'')).slice(0,6),perf=document.getElementById('progressList');perf.insertAdjacentHTML('afterbegin',`<h3>Concept2</h3>${imported.map(row=>`<p>${c2Date(row)}: ${c2Machine(row.type)} · ${c2Summary(row)}</p>`).join('')}`)}renderConcept2()};
document.getElementById('syncConcept2').onclick=syncConcept2;renderC2Day();
